### ISSUE TITLE
Dumb question

### ISSUE THREAD

**Issue by ghost** [maximbilan/iOS-Shared-CoreData-Storage-for-App-Groups#1]
This has a relationship to background services running on iOS ?

I read that apple only allows them to run for 10 minutes and then kills them which is nice of them :)

**Comment by maximbilan** [comment]
@gedw99 No, it's another stuff. App group it's for using one storage for some apps, in my example it's one main application and today extension and both of them use one storage. It's no related to background running.

**Comment by ghost** [comment]
Thanks.

I need to do background processing where I call the server even if all the
foreground apps are closed.
That's where the 10 minute kill comes in :)

So I guess the background service could also participate with the data
sharing between apps too ?
