### ISSUE TITLE
Data Sharing With Watch App

### ISSUE THREAD

**Issue by ghost** [maximbilan/iOS-Shared-CoreData-Storage-for-App-Groups#3]
Hi, 

We are facing the issue while reading data with my iPhone application (watch OS 3). Could you please help me how I will do the same.

**Comment by maximbilan** [comment]
hi @muneesh-kiwitech 

Thanks for using the tutorial.
I can find a note about watchOS in the ending of the description.

NOTE: In watchOS 2 and higher you should have to maintain two separate data stores. Group identifier is not working in this case. If either side is a "read-only" client and the CoreData datastore is small and changes infrequently you could potentially use the transferFile WatchConnectivity API to transfer the whole store each time it changes.

So, the approach described in the tutorial can't work properly with watchOS 3.

**Comment by daviddelmonte** [comment]
Hi Maxim, is this still the case in watchOS5? Thanks

**Comment by maximbilan** [comment]
Hi @daviddelmonte,

Yes, doesn't work in watchOS 5. Use [WatchConnectivity](https://developer.apple.com/documentation/watchconnectivity). Happy coding!

**Comment by daviddelmonte** [comment]
Thanks Maxim. Got it.
